### PR TITLE
ADD CONTRIBUTOR GUIDE SECTION

### PR DESCRIPTION
**Pull request by alo7lika**
Closes: #356 

# Description of changes:
A Contributor Guide is essential for fostering a collaborative and efficient open-source community. By providing clear instructions and expectations, it eliminates ambiguity and helps potential contributors understand how to get involved in the project. This guide ensures consistency in contributions, which is crucial for maintaining the project's integrity and quality. Furthermore, it encourages communication among contributors and maintainers, making the onboarding process smoother for newcomers. With a structured approach to contributions, the project can benefit from diverse perspectives and skill sets, ultimately leading to a richer development experience and a more robust final product.

# Issue Reference:
- Issue #356

### CODE REVIEW

**Comment by alo7lika** [comment]
@sakeel-103  the task has been completed.

**Comment by alo7lika** [comment]
Screenshot 2024-10-20 180149
ADD LABELS ON PR

**Review by sakeel-103 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad can you review this PR?

**Review by MastanSayyad — COMMENTED** [review]
hi @sakeel-103 readme docs changes can only have level 1 label

**Pull request merged**
