### PR TITLE
SORTING VISUALIZER OF ALL THE SORTIGN ALGORITHEM

### PR DESCRIPTION
**Pull request by Meetpidev**
# 🛠️ Fixes Issue
Fixes: #447 

# 👨‍💻 Description
ITS INCLUDES ALL THE SORTING ALGORITHM. WE CAN VISUALIZE SORTING ALGORITHMS ..

# 📄 Type of Change
- New feature (non-breaking change which adds functionality)

# 📷 DEMO
https://github.com/user-attachments/assets/86b53bd6-65dd-4bce-aa7f-0e786404c653

# ✅ Checklist
- [ YES ] I am a participant of GSSoC-ext.
- [ YES ] I have followed the contribution guidelines of this project.
- [ YES ] I have viewed deployment of my code.
- [ YES ] My changes generate no new warnings.
- [ YES ] I have made this change from my own.
- [ YES ] I have taken help from some online resources.
- [ YES ] My code follows the style guidelines of this project.
- [ YES ] I have performed a self-review of my own code.
- [ YES ] I have added documentation to explain my changes.

# 🤝 GSSoC Participation
- [ YES ] This PR is submitted under the GSSoC program.
- [ YES ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Meetpidev** [comment]
@sakeel-103 Please Review PR..

**Comment by Meetpidev** [comment]
@sakeel-103  Request to accept it with level-3 under gssoc as its includes all the algorithm with visual formate and we can also take new array and we can control speed of visualing...

**Review by sakeel-103 — APPROVED** [review]

**Comment by sakeel-103** [comment]
@Meetpidev 
The project is based on DFS and BFS traversal or visualization. However, I had assigned you this implementation because of the Visualization algorithms. 
This algorithm should be in a different page should not be in the DFS-BFS algorithm page.
I hope you added like this.

**Comment by sakeel-103** [comment]
@Meetpidev 
bro can you provide a video of this implementation where you added.

**Comment by Meetpidev** [comment]
@sakeel-103 By mistake i added it in DFS rout.. now i fixed it..

**Comment by Meetpidev** [comment]
@sakeel-103 i created separate rout for this because it contains all sorting algorithem..

**Comment by Meetpidev** [comment]
@sakeel-103 Requested to review again

**Comment by Meetpidev** [comment]
@sakeel-103 Please review PR..

**Comment by Meetpidev** [comment]
@sakeel-103 Requested to review and accept it with leve-3 label as it includes all the sorting algo with visualizations

**Comment by Meetpidev** [comment]
@sakeel-103  Requested to review

**Comment by Meetpidev** [comment]
@sakeel-103 please review PR..

**Pull request merged**
