### PR TITLE
Enhance Session Security

### PR DESCRIPTION
**Pull request by muskan171105**
**Changes Introduced:**

1. **Session Security Enhancements:**

(a) Implemented secure cookie settings:
-Set httpOnly to prevent client-side access to cookies.
-Set secure to true when in production, ensuring cookies are only sent over HTTPS.

(b) Ensured better session management for improved security during user interactions.

These updates help protect user sessions and reduce potential vulnerabilities.

### CODE REVIEW

**Comment by sakeel-103** [comment]
@muskan171105 
plz mention issue number

**Comment by muskan171105** [comment]
I have directly created a pull request. If u want I can raise an issue and then can mention it here

**Comment by sakeel-103** [comment]
@muskan171105 
srry to say it won't be considered if u do a PR without assign or an issue
First raise issue then do PR after assigning

**Comment by muskan171105** [comment]
Ok. I apologize for not following the procedure properly. I will do it rightaway

**Pull request merged**
