### PR TITLE
 Add trailing dots cursor effect for Enhanced User Experience done ! #590 🌟🌟

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add trailing dots cursor effect for Enhanced User Experience done - #590 

https://github.com/user-attachments/assets/22f4fcea-d7c6-411d-8f90-b78db7ca7775

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.
# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 sir at least give me level 2.. If you check other projects they give level 3/2 for this.. you can check

**Comment by mehul-m-prajapati** [comment]
@Subhajit-2023-44 : it does not work #603

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 : it does not work #603

@mehul-m-prajapati what ?? send video..

**Comment by mehul-m-prajapati** [comment]
@Subhajit-2023-44 

https://github.com/user-attachments/assets/3e8f6c5a-7e35-4f4b-92c4-304c0f2b312e

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44
> 
>  bandicam.2024-11-09.12-55-08-682.mp4

This is not the home page..

**Comment by mehul-m-prajapati** [comment]
Does not matter -> 
This is bad code -> It hides cursor at all places


/* Hide default cursor */
html, body, html * {
    cursor: none;
}

**Pull request merged**
