### PR TITLE
fix api endpoints and data leaking

### PR DESCRIPTION
**Pull request by rudrapratap63**
Fix issue #59 and also remove the password storing functionality from localStorage, and create environment files for better configuration."

https://github.com/user-attachments/assets/4df67b19-834a-44b0-9297-288aa54bc6eb

### CODE REVIEW

**Comment by rudrapratap63** [comment]
@sakeel-103 Please check the PR

**Comment by rudrapratap63** [comment]
@sakeel-103 , could you please let me know what API URL to add in the environment.prod.ts file?

image

**Comment by sakeel-103** [comment]
@rudrapratap63 
Awesome, you have provided good explanation of you work.

**Review by sakeel-103 — APPROVED** [review]

**Comment by rudrapratap63** [comment]
> @rudrapratap63 Awesome, you have provided good explanation of you work.
Thank you so much, @sakeel-103 , I'm glad you liked my work and the explanation provided. If there's any other contribution I can make or if you have any specific tasks in mind, feel free to let me know. I'm happy to help!

**Pull request merged**
