### PR TITLE
Added custom graph creation feature

### PR DESCRIPTION
**Pull request by LifeHashed**
Now on input custom graph will be generated. Although there is a format specified. Please test and tell me if changes are necessary

### CODE REVIEW

**Comment by sakeel-103** [comment]
Sorry, I'm bury with my exams. 
here I only checked the community violence.
Later on, I'll definitely do

**Comment by sakeel-103** [comment]
Could You plz Show me the SS of the output what changes you have done.

**Comment by sakeel-103** [comment]
The output of the traversal does not look good .
So I'm reverting the PR.
please work on it  and do the PR again

**Comment by LifeHashed** [comment]
https://github.com/user-attachments/assets/6507c9ea-5d17-4ccd-a756-e0d44984a133

This is the demo

**Comment by sakeel-103** [comment]
@LifeHashed 
Could you please do the PR

**Comment by LifeHashed** [comment]
Without any changes?

**Comment by sakeel-103** [comment]
No, make changes to the graph so that it resembles a tree structure. This way, the DFS and BFS traversal will clearly display the nodes.

**Comment by LifeHashed** [comment]
But if cycles exist then how can graph be a tree?

**Comment by sakeel-103** [comment]
reverted PR cannot be merged back.
do one thing delete this pr and create a new one.

**Comment by LifeHashed** [comment]
Ok trying. Will let you know

**Pull request merged**
