### PR TITLE
Redesigning of Footer and Responsiveness Addition | Issue #319

### PR DESCRIPTION
**Pull request by Shariq2003**
I have redesigned the footer and also added responsiveness in the footer.

Before and After :

https://github.com/user-attachments/assets/dcc0bdf3-3210-4ff5-8004-105050594601

Completed #319

### CODE REVIEW

**Comment by sakeel-103** [comment]
@Shariq2003 
Resolve the conflict problem

**Comment by Shariq2003** [comment]
> @Shariq2003 Resolve the conflict problem

Okay doing

**Comment by Shariq2003** [comment]
> @Shariq2003 Resolve the conflict problem

@sakeel-103 sir, please review and merge

**Review by MastanSayyad — COMMENTED** [review]
Code is formatted and all code is same only few CSS has been added 

image

and Copyright section is separated with no changes

image

**Pull request merged**
