### PR TITLE
Redesign the Whole Quiz Page | Enhance the Quiz Page | Issue #345

### PR DESCRIPTION
**Pull request by Shariq2003**
# 🛠️ Fixes Issue
Fixes: #345 

# 👨‍💻 Description
 I have completely redesigned the whole quiz page and made it visually appealing.
Added a Sidebar for Difficulty.
Enhance the Result Container.

Overall Redesign and Enhance the Quiz Page.

# 📄 Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/57ded649-48cf-4f84-a730-59cf8d04d271

# ✅ Checklist
- [X] I am a participant of GSSoC-ext.
- [X] I have followed the contribution guidelines of this project.
- [X] I have viewed deployment of my code.
- [X] My changes generate no new warnings.
- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have added documentation to explain my changes.

# 🤝 GSSoC Participation
- [X] This PR is submitted under the GSSoC program.
- [X] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Shariq2003** [comment]
@sakeel-103 sir please review and merge this.

**Review by sakeel-103 — APPROVED** [review]

**Comment by sakeel-103** [comment]
@Shariq2003 
resolve the conflict issue

**Comment by Shariq2003** [comment]
> @Shariq2003 resolve the conflict issue

@sakeel sir, okay I am fixing the conflicts, but after that, you have to merge this first because if you merge a person's code with the previous quiz UI code, then it will again raise conflicts in this PR.

**Comment by Shariq2003** [comment]
> @Shariq2003 resolve the conflict issue

Sir, please review and merge

**Comment by Shariq2003** [comment]
@sakeel-103 any other page that i can enhance please let me know.

**Pull request merged**
