### PR TITLE
Add/Enable PWA (Progressive Web App) done ! #589 🔵🌟

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add/Enable PWA (Progressive Web App) done - #589 🟢🌟

🟢Key Features of PWAs:

🔵Offline Capability: Using service workers, PWAs can function offline or in low-network conditions by caching essential assets.
🔵App-like Experience: PWAs behave like native apps, with smooth animations, navigation, and interactions, even on mobile.
🔵Push Notifications: PWAs can send push notifications to engage users, even when the app is not open.
🔵Installability: PWAs can be installed on the user’s home screen, just like a native app, without going through app stores.
🔵Fast Loading: By caching resources and using service workers, PWAs can load quickly, even with slow network conditions.
🔵Responsive: They adapt to any device, whether it's a mobile, tablet, or desktop.

Screenshot 2024-11-10 010651
Screenshot 2024-11-10 010759

https://github.com/user-attachments/assets/cfa0e423-0603-41a5-9df2-3844a6dadcf1

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by mehul-m-prajapati** [comment]
@Subhajit-2023-44 : What is the exact use case? What happens after you press install ?

**Comment by Subhajit-2023-44** [comment]
@sakeel-103

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 please merge and add level

**Comment by mehul-m-prajapati** [comment]
@Subhajit-2023-44 what is your discord profile name

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 what is your discord profile name


Screenshot 2024-11-10 192411

@mehul-m-prajapati you know the reason ? Why are you not in the top 10?

check to leaderboard 7th contributors profile, totally spam

**Comment by mehul-m-prajapati** [comment]
I know. There are 3 spammers in top 10

**Comment by Subhajit-2023-44** [comment]
> I know. There are 3 spammers in top 10

what ??

**Comment by Subhajit-2023-44** [comment]
Screenshot 2024-11-10 184515
Screenshot 2024-11-10 184640
Screenshot 2024-11-10 184648

**Comment by mehul-m-prajapati** [comment]
Srija and haseeb are also spammers

**Comment by Subhajit-2023-44** [comment]
> Srija and haseeb are also spammers

😱😱

**Comment by Subhajit-2023-44** [comment]
Its not good 😭

**Comment by Subhajit-2023-44** [comment]
Screenshot 2024-11-10 184146

**Comment by mehul-m-prajapati** [comment]
That sums up cheap quality of this orogram

**Comment by Subhajit-2023-44** [comment]
> That sums up cheap quality of this orogram

next time i don't contribute here again, totally time waste,

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 what is your discord profile name

subhajit_7

**Comment by Subhajit-2023-44** [comment]
> I know. There are 3 spammers in top 10

Hey @mehul-m-prajapati No need to thank me 😏

Screenshot 2024-11-11 133700

**Comment by mehul-m-prajapati** [comment]
Come on discord VC. You are about to get penalties

**Pull request merged**
