### PR TITLE
Add review and questions page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
Screenshot 2024-10-17 at 10 36 12 PM
I have kept it minimilistic and tried making it functional

### CODE REVIEW

**Comment by sakeel-103** [comment]
@shubhagarwal1 
 header.component.html file has a conflict. Please resolve it. Also, please change the page color as the dark color doesn't look good.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 header.component.html file has a conflict. Please resolve it. Also, please change the page color as the dark color doesn't look good.

okay working onit

**Comment by shubhagarwal1** [comment]
i have solve the conflicts 
@sakeel-103

**Comment by shubhagarwal1** [comment]
Hey @sakeel-103 do you have anything specific in your mind tha cn be implemented

**Comment by sakeel-103** [comment]
@shubhagarwal1 
Sure, why not.
You can work on **topological sorting**. 
like - 
DFS and Source Removal which are apply only on DAG approach.
Bcz the name of this project is hanged from DFS-BFS to GraphExplorer. So, you can work on different type graphs

**Review by sakeel-103 — APPROVED** [review]

**Comment by sakeel-103** [comment]
@shubhagarwal1 
please mention the issue number here.

**Pull request merged**
