### PR TITLE
Integrated NQueen Visualizer | Issue #498

### PR DESCRIPTION
**Pull request by Shariq2003**
# 🛠️ Fixes Issue
Fixes: #498

# 👨‍💻 Description
I have successfully integrated my project, the N-Queen Visualiser into the WebApp.

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots/GIFs (if any)

image
image
image

https://github.com/user-attachments/assets/886e28c1-acb6-438a-9ff4-9dd088cc18a0

# ✅ Checklist
- [X] I am a participant of GSSoC-ext.
- [X] I have followed the contribution guidelines of this project.
- [X] I have viewed deployment of my code.
- [X] My changes generate no new warnings.
- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have added documentation to explain my changes.

# 🤝 GSSoC Participation
- [X] This PR is submitted under the GSSoC program.
- [X] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Shariq2003** [comment]
@sakeel-103 sir, i have successfully integrate my project.
Please review.

**Comment by sakeel-103** [comment]
@Shariq2003 
resolve the conflicts

**Comment by Shariq2003** [comment]
@sakeel-103 sir, please review again

**Comment by mehul-m-prajapati** [comment]
N-Queen is related to backtracking algorithm. How is it related to bfs-dfs ?
What is the reason of putting it in navbar @Shariq2003 ?

**Comment by Shariq2003** [comment]
> N-Queen is related to backtracking algorithm. How is it related to bfs-dfs ? What is the reason of putting it in navbar @Shariq2003 ?

So how a user can navigate to that sir.

**Comment by Shariq2003** [comment]
> N-Queen is related to backtracking algorithm. How is it related to bfs-dfs ? What is the reason of putting it in navbar @Shariq2003 ?

DFS-BFS Visualizer is an Visualizer that Visualize the DFS and BFS algorithms, similarly N-Queen Visualizer also Visualize the N-Queen Problem so that user can also visualize it easily and putting it in Navbar for Navigating @mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
@Shariq2003 : yeah, good work. Maybe you should rename the project from bfs-dfs to algorithm visualizer.

**Comment by Shariq2003** [comment]
> N-Queen is related to backtracking algorithm. How is it related to bfs-dfs ? What is the reason of putting it in navbar @Shariq2003 ?

@mehul-m-prajapati have you any idea about backtracking algorithms, DFS and BFS algorithms also use backtracking to traverse the Trees and Graph

image



@mehul-m-prajapati please also read this to understand BFS and DFS

https://stackoverflow.com/questions/2709030/explain-bfs-and-dfs-in-terms-of-backtracking

**Comment by Shariq2003** [comment]
ppreciate the input, @mehul-m-prajapati . Happy to adjust the repo name if it helps you understand the contents better, 
Since N-Queen involves recursive exploration like DFS, it belongs here; a quick review of algorithm fundamentals should help clear things up, If you're unsure how N-Queen connects with graph algorithms, perhaps exploring the basics of backtracking, DFS, and BFS might clarify why it's in the navbar.

**Comment by Shariq2003** [comment]
> @Shariq2003 : yeah, good work. Maybe you should rename the project from bfs-dfs to algorithm visualizer.

Appreciate the input, @mehul-m-prajapati . Happy to adjust the repo name if it helps you understand the contents better, 
Since N-Queen involves recursive exploration like DFS, it belongs here; a quick review of algorithm fundamentals should help clear things up, If you're unsure how N-Queen connects with graph algorithms, perhaps exploring the basics of backtracking, DFS, and BFS might clarify why it's in the navbar.

**Comment by shubhagarwal1** [comment]
> N-Queen is related to backtracking algorithm. How is it related to bfs-dfs ?

The N-Queen problem is primarily solved using the backtracking algorithm, which is a depth-first approach. Backtracking explores possible solutions by going as deep as possible along a branch (similar to DFS) and backtracking when it hits a dead end. While BFS isn’t typically used for N-Queen due to its exhaustive nature and space requirements, DFS-style recursion fits naturally since we explore one potential queen placement at a time, backtrack, and then try alternate paths

**Comment by mehul-m-prajapati** [comment]
Thanks for teaching me about N-Queen algorithm with dfs. I just got some more ideas for this project

- Sudoku solver #530
- Graph coloring #531
- 8-puzzle : Up for grabs

**Comment by Shariq2003** [comment]
> Thanks for teaching me about N-Queen algorithm with dfs. I just got some more ideas for this project
> 
> * Sudoku solver [Add sudoku solver #530](https://github.com/sakeel-103/DFS-BFS-Graph-Travers/issues/530)
> * Graph coloring [Add Graph coloring visualizer  #531](https://github.com/sakeel-103/DFS-BFS-Graph-Travers/issues/531)
> * 8-puzzle : Up for grabs

Thank you for the suggestion, @mehul-m-prajapati  sir. However, I prefer to integrate the project that I’ve personally created in HTML, CSS, and JavaScript (Link: [N-Queen Visualiser](https://github.com/Shariq2003/N-Queen-Visualiser)). This approach allows me to gain hands-on experience in converting my code into Angular components, enhancing my skills, and giving me the satisfaction of building the project myself, rather than relying on external sources.

Thanks for Suggestion @mehul-m-prajapati sir.

**Comment by sakeel-103** [comment]
@Shariq2003 
@mehul-m-prajapati 
@shubhagarwal1

Thank you for your thoughtful approach and insights and you guys know better than me about this.
Her I just want to point out that the N-Queens problem is related to DFS, which is a type of backtracking algorithm. That’s why I approved this approach.

reference -
Screenshot 2024-11-02 223343

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : Yeah, it is related to DFS. I think it should not be in the navbar along with BFS, DFS visualization.
Maybe we can add that in landing page or somewhere else.

**Comment by Shariq2003** [comment]
> @sakeel-103 : Yeah, it is related to DFS. I think it should not be in the navbar along with BFS, DFS visualization. Maybe we can add that in landing page or somewhere else.

Okay, if @sakeel-103 sir, wants to add the navigating to this page somewhere else, then I will add
No problem

**Comment by Shariq2003** [comment]
> @Shariq2003 @mehul-m-prajapati @shubhagarwal1
> 
> Thank you for your thoughtful approach and insights and you guys know better than me about this. Here I just want to point out that the N-Queens problem is related to DFS, which is a type of backtracking algorithm. That’s why I approved this approach.
> 
> reference - Screenshot 2024-11-02 223343

Yes sir, so please review my implementation and merge

**Comment by Shariq2003** [comment]
> @sakeel-103 : Yeah, it is related to DFS. I think it should not be in the navbar along with BFS, DFS visualization. Maybe we can add that in landing page or somewhere else.

No, it should be in the Navbar for better Navigating

**Comment by sakeel-103** [comment]
> @sakeel-103 : Yeah, it is related to DFS. I think it should not be in the navbar along with BFS, DFS visualization. Maybe we can add that in landing page or somewhere else.

@mehul-m-prajapati 
yes, it's correct I think it should not be in the DFS-BFS page, it should be in separate page 

@Shariq2003 
I apologize for this, if possible, could you please add this N-Queens problem visualizer button in the navbar here, alongside DFS-BFS.
Screenshot 2024-11-02 230423

And when a user clicks the navigating button here, then it should open N-Queen visualizer on separate page dedicated solely to N-Queens problems, without DFS-BFS problem. 
like N-Queens visualizer shouldn't be in this page.
Screenshot 2024-11-02 230555

**Comment by Shariq2003** [comment]
> > @sakeel-103 : Yeah, it is related to DFS. I think it should not be in the navbar along with BFS, DFS visualization. Maybe we can add that in landing page or somewhere else.
> 
> @mehul-m-prajapati yes, it's correct I think it should not be in the DFS-BFS page, it should be in separate page
> 
> @Shariq2003 I apologize for this, if possible, could you please add this N-Queens problem visualizer button in the navbar here, alongside DFS-BFS. Screenshot 2024-11-02 230423
> 
> And when a user clicks the navigating button here, then it should open N-Queen visualizer on separate page dedicated solely to N-Queens problems, without DFS-BFS problem. like N-Queens visualizer shouldn't be in this page. Screenshot 2024-11-02 230555

okay sure, sir no problem
Just give me 5 mints

**Comment by Shariq2003** [comment]
@sakeel-103 sir can we connect over discord VC  for better communication,

**Comment by sakeel-103** [comment]
> @sakeel-103 sir can we connect over discord VC for better communication, Please ping me by my username or just connect on general
> 
> Shariq

Where ?

**Comment by Shariq2003** [comment]
> > @sakeel-103 sir can we connect over discord VC for better communication, Please ping me by my username or just connect on general
> > Shariq
> 
> Where ?

general VC

**Comment by Shariq2003** [comment]
@sakeel-103 sir, please share your discord username, I will msg you

**Comment by Shariq2003** [comment]
> > @sakeel-103 : Yeah, it is related to DFS. I think it should not be in the navbar along with BFS, DFS visualization. Maybe we can add that in landing page or somewhere else.
> 
> @mehul-m-prajapati yes, it's correct I think it should not be in the DFS-BFS page, it should be in separate page
> 
> @Shariq2003 I apologize for this, if possible, could you please add this N-Queens problem visualizer button in the navbar here, alongside DFS-BFS. Screenshot 2024-11-02 230423
> 
> And when a user clicks the navigating button here, then it should open N-Queen visualizer on separate page dedicated solely to N-Queens problems, without DFS-BFS problem. like N-Queens visualizer shouldn't be in this page. Screenshot 2024-11-02 230555

Yes sir, I have already done that, please review.

**Comment by Shariq2003** [comment]
@sakeel-103 sir, I have made the changes as per the requirements

**Pull request merged**
