### PR TITLE
Fixes: #303 - Jashwanth/faq/contributor/review

### PR DESCRIPTION
**Pull request by Jashwanth-rit**
Fixes: #303 

this PR makes sure that , Theme correction has been done , which is more attractive and premium.

contributors-page:

https://github.com/user-attachments/assets/c783a5a6-f3d9-43f4-8dd2-c2337c4bd727

Faq-page:

https://github.com/user-attachments/assets/04a9459e-a075-4f5a-95e1-6e33edaaa486

review-page:

https://github.com/user-attachments/assets/2402729e-a46f-4339-9a23-1975b56b6d1f

### CODE REVIEW

**Review by sakeel-103 — APPROVED** [review]

**Comment by Jashwanth-rit** [comment]
Bro I have doubt Regarding this Gssoc ,

**Comment by sakeel-103** [comment]
> Bro I have doubt Regarding this Gssoc ,

ok ask

**Comment by Jashwanth-rit** [comment]
Bro if We contribute in unselected projects will they give us points or not
Like Today they have announced about selected projects , there 37 projects , should we need to contribute in that only or we can contribute any .

**Comment by Jashwanth-rit** [comment]
https://docs.google.com/spreadsheets/u/0/d/1zWEn_AWEYaEZQrVl2VFUvFoASnhIIwPOqqwAePR3Luk/htmlview

here is the link to watchout that projects

**Pull request merged**
