### PR TITLE
added footer contact us modal and done fixes in language translator

### PR DESCRIPTION
**Pull request by ananyag309**
#144 
I have added contact us modal - with valid validation, colur theme, proper allignment Not only this contact us form is available in different language as well.

contact us forum:

image

image

working of contact us modal:

https://github.com/user-attachments/assets/a1412c12-9155-49c1-a978-c0678d789376

contact us form in different languages working modal:

https://github.com/user-attachments/assets/60d23460-067a-43aa-9b99-9afb80157ed2

### CODE REVIEW

**Comment by sakeel-103** [comment]
https://github.com/user-attachments/assets/176008e9-cc23-4689-9422-15623a52ec73

The output isn't showing in the deployment

**Comment by ananyag309** [comment]
@sakeel-103 can you check and tell me is there any other component too where i need to make changes cuz its working on my pc - can you try running header component once

**Comment by ananyag309** [comment]
@sakeel-103 i have gone through the code the header component html file and the website is working locally, but not on deployed version i will be working on it, ig some fixes need to be done in other files. Right now i am just left with 1 more exam, so i need some time, but i ensure you it will be done soon

**Comment by sakeel-103** [comment]
@ananyag309 
Srry to say, but I'm currently busy with my exams. I haven't reviewed the code properly; I just checked for conflict issues and merged the changes. Please go through it and make any necessary corrections if needed.
N thank u for yur contribution on this projects.

**Comment by ananyag309** [comment]
okay sure

**Pull request merged**
