### PR TITLE
added language translator 

### PR DESCRIPTION
**Pull request by ananyag309**
#160 
added language translator for english hindi french german and spanish

image

working demo video:

https://github.com/user-attachments/assets/891bf545-78ba-479b-8e54-6dfc66ec0982

### CODE REVIEW

**Review by sakeel-103 — APPROVED** [review]

**Comment by sakeel-103** [comment]
Awesome !

**Comment by sakeel-103** [comment]
@ananyag309 
your changes and the implementation of the language translator are not working after being merged with the design when the language is changed. Please review your code once.

**Comment by ananyag309** [comment]
okay let me check

**Comment by sakeel-103** [comment]
plz once check the deployment !

And one request, is it possible to add Kannada language if then plz add it.

**Comment by ananyag309** [comment]
yes i will add kannada also

**Comment by sakeel-103** [comment]
@ananyag309 
then raise one issue and add there more languages which are spoken in India.

**Pull request merged**
