### PR TITLE
Make Footer Styled

### PR DESCRIPTION
**Pull request by Meetpidev**
# 🛠️ Fixes Issue
Fixes: #437 

# 👨‍💻 Description
Improve styling of footer..

# 📄 Type of Change
- Bug fix (non-breaking change which fixes an issue)

# 📷 Screenshots/GIFs (if any)
### From This :
image
### To This: 
image

# ✅ Checklist
- [ YES ] I am a participant of GSSoC-ext.
- [ YES ] I have followed the contribution guidelines of this project.
- [ YES ] I have viewed deployment of my code.
- [ YES ] My changes generate no new warnings.
- [ YES ] I have made this change from my own.
- [ YES ] I have taken help from some online resources.
- [ YES ] My code follows the style guidelines of this project.
- [ YES ] I have performed a self-review of my own code.
- [ YES ] I have added documentation to explain my changes.

# 🤝 GSSoC Participation
- [ YES ] This PR is submitted under the GSSoC program.
- [ YES ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Meetpidev** [comment]
@sakeel-103 Requested to review PR...

**Comment by Meetpidev** [comment]
@sakeel-103 Please Review PR..

**Review by sakeel-103 — APPROVED** [review]

**Comment by sakeel-103** [comment]
@Meetpidev 
Brother, I’m sorry to say that your changes don’t meet the required standard. In fact, I can’t even give you a level 1 mark.
It would be better if you add something or change here.

**Comment by Meetpidev** [comment]
@sakeel-103 Can i add social links like linkedin github twiter?

**Comment by Meetpidev** [comment]
@sakeel-103 
### Can i put the Down arrow ? like this up arrow ? its useful if someone wants to only discuss.. or see all the social accounts.. 
image

**Comment by Meetpidev** [comment]
@sakeel-103 Please Review Again..
### Make footer more styled.. and perfect alignments...Added GithHub link
Screenshot 2024-11-03 011630
https://github.com/user-attachments/assets/d26b9a1d-e419-4409-9b17-7ed2a0dc92f3

### improve contactPage styling.. 
Screenshot 2024-11-03 010622

**Comment by Meetpidev** [comment]
@sakeel-103 Requested to review again

**Comment by Meetpidev** [comment]
@sakeel-103 Please Review PR...

**Comment by Meetpidev** [comment]
@sakeel-103 Please Review PR..

**Review by sakeel-103 — APPROVED** [review]

**Pull request merged**
