### PR TITLE
Add navbar to FAQ page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #186 
Screenshot 2024-10-14 at 9 14 31 PM

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
minor changes remove level  labels @sakeel-103

**Comment by shubhagarwal1** [comment]
> minor changes remove level labels @sakeel-103

for minor doucmentation changes, even for adding one line we give level 1 then why no labels on this @MastanSayyad, why the review is so harsh.

**Comment by MastanSayyad** [comment]
Nope I never said docs with one line will have labels, it will have no levels @shubhagarwal1 And see you are top Contributor with rank 1 and 140+ merged PRs we have to be harsh for such PRs, dont worry you are not the only one here, I'm doing this all top 10

But yeah closely with top 3!

**Comment by shubhagarwal1** [comment]
> Nope I never said docs with one line will have labels, it will have no levels @shubhagarwal1 And see you are top Contributor with rank 1 and 140+ merged PRs we have to be harsh for such PRs, dont worry you are not the only one here, I'm doing this all top 10
> 
> But yeah closely with top 3!
Got it, thanks for holding us to a high standard. I'll make sure to keep an eye on these details going forward!"

**Pull request merged**
