### PR TITLE
WIP: Add logout in profile dropdown

### LINKED ISSUE #61: Profile dropdown menu goes out of alignment
c2

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
- A profile dropdown is not needed at this time
closes #61

### CODE REVIEW

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Apologies for the confusion, but there should be a dropdown for the user's profile. The logout function should be placed within the dropdown, so after the user logs in, they can access their profile and log out from there. So, I think the functions should be like this.

**Comment by mehul-m-prajapati** [comment]
> @mehul-m-prajapati Apologies for the confusion, but there should be a dropdown for the user's profile. The logout function should be placed within the dropdown, so after the user logs in, they can access their profile and log out from there. So, I think the functions should be like this.

@sakeel-103 - okay, I will create a profile dropdown in this PR

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Thank you for dedicating your valuable time to this project.

**Comment by sakeel-103** [comment]
Apologize for this,
Could you please provide a demo of the output from your implementation regarding this issue ?

**Pull request closed without merging**
