### PR TITLE
Add a User Profiles page done ! #588 🌟🌟🌟 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add a User Profiles page done - #588 

https://github.com/user-attachments/assets/44cbfce7-9c8a-463b-8e58-aa7cacc94a17

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.x
# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 PA please merge my PR with level 3

**Review by sakeel-103 — APPROVED** [review]

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 sir level 2 is too low for this work, please upgrade the level 2 to 3.. if you check other projects they also give level 3 for this, you can check my code, i have added a lot...


 
Screenshot 2024-11-03 001321
Screenshot 2024-11-03 121147
image

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 sir level 2 is too low for this work, please upgrade the level 2 to 3.. if you check other projects they also give level 3 for this, you can check my code, i have added a lot...

image

 
Screenshot 2024-11-03 001321
image

**Comment by Subhajit-2023-44** [comment]
@sakeel-103

**Comment by mehul-m-prajapati** [comment]
@Subhajit-2023-44 : you are not in control to decide levels. Respect what is given to you by @sakeel-103

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : This is just sample page which is added in footer 

The correct implementation should be to add in navbar -> Add edit option which sends request to backend to update profile details.

You can add level1 or remove it as Edit profile issue is there #602

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 : you are not in control to decide levels. Respect what is given to you by @sakeel-103

Of course, gssoc-ext project admin consider it as a level 3 work..

**Comment by Subhajit-2023-44** [comment]
> @sakeel-103 : This is just sample page which is added in footer
> 
> The correct implementation should be to add it in navbar -> Add edit option which sends request to backend to update profile details.
> 
> You can add level1 or remove it as Edit profile issue is there #602

@mehul-m-prajapati Sir what is your problem?   Are you the admin of this project or not?   Did you know 1 week ago gssoc project admin closes a project and removes his all levels who contribute to the same project as admins and contributors...

**Comment by Subhajit-2023-44** [comment]
> @sakeel-103 : This is just sample page which is added in footer
> 
> The correct implementation should be to add it in navbar -> Add edit option which sends request to backend to update profile details.
> 
> You can add level1 or remove it as Edit profile issue is there #602

Screenshot 2024-11-09 234822

And its a level 3 work, if you don't know then check other projects...

**Comment by mehul-m-prajapati** [comment]
My problem is with people like you who are opening unnecessary issues to gain points. @Subhajit-2023-44

**Comment by Subhajit-2023-44** [comment]
> My problem is with people like you who are opening unnecessary issues to gain points. @Subhajit-2023-44

btw i know the proper reason.. 😂

**Comment by Subhajit-2023-44** [comment]
> My problem is with people like you who are opening unnecessary issues to gain points. @Subhajit-2023-44

then you check can check other projects and contributors.... 😂

**Comment by mehul-m-prajapati** [comment]
@Subhajit-2023-44 : Do you really think adding a sample page in footer is level3 ?
d1

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 : Do you really think adding a sample page in footer is level3 ? d1

in footer ???

**Comment by mehul-m-prajapati** [comment]
f1

**Comment by mehul-m-prajapati** [comment]
> > > @sakeel-103 : This is just sample page which is added in footer
> > > The correct implementation should be to add it in navbar -> Add edit option which sends request to backend to update profile details.
> > > You can add level1 or remove it as Edit profile issue is there #602
> > 
> > 
> > @mehul-m-prajapati Sir what is your problem? Are you the admin of this project or not? Did you know 1 week ago gssoc project admin closes a project and removes his all levels who contribute to the same project as admins and contributors...
> 
> @mehul-m-prajapati Are you the admin of this project or not?

@Subhajit-2023-44 : Yes, I am a virtual mentor. What is your discord profile name ?

**Comment by Subhajit-2023-44** [comment]
> f1

its profile page link

**Comment by Subhajit-2023-44** [comment]
> > > > @sakeel-103 : This is just sample page which is added in footer
> > > > The correct implementation should be to add it in navbar -> Add edit option which sends request to backend to update profile details.
> > > > You can add level1 or remove it as Edit profile issue is there #602
> > > 
> > > 
> > > @mehul-m-prajapati Sir what is your problem? Are you the admin of this project or not? Did you know 1 week ago gssoc project admin closes a project and removes his all levels who contribute to the same project as admins and contributors...
> > 
> > 
> > @mehul-m-prajapati Are you the admin of this project or not?
> 
> @Subhajit-2023-44 : Yes, I am a virtual mentor. What is your discord profile name ?

see this - 
Screenshot 2024-11-09 235802

@mehul-m-prajapati sir i will give you my my discord profile name tomorrow, please don't waste my time today ..
sir in future i may be need your help as i am a beginner

**Comment by Subhajit-2023-44** [comment]
image

**Pull request merged**
