### PR TITLE
fixed the explore button and improved the style of homepage.

### PR DESCRIPTION
**Pull request by adityakalburgi**
I fixed the explore button redirect issue and also improved the style of homepage(header file) by changing background, adding hover effect etc.
resolves issue #11

### CODE REVIEW

**Comment by sakeel-103** [comment]
this pr has failed to deploy, please check the errors.

**Comment by adityakalburgi** [comment]
> this pr has failed to deploy, please check the errors.

ok working on it

**Comment by adityakalburgi** [comment]
Hi @sakeel-103 i have fixed the errors.

**Comment by adityakalburgi** [comment]
Hi @sakeel-103 please change the labels of PR from "Level1" to "Level1" change L to small l as per gssoc-ext guidelines thank you..

**Comment by sakeel-103** [comment]
@adityakalburgi 
thanks for reminding !

**Pull request merged**
