### PR TITLE
Fix Login  Functionality and Redirect Logic

### PR DESCRIPTION
**Pull request by Dipu2552003**
**Resolved Login Functionality:** 
issue number #38  @sakeel-103 
The _login button in the HTML was previously not properly linked to the TypeScript file, _resulting in an unintended direct redirect_.__ **This has been fixed to ensure that the login button now correctly triggers the authentication process before redirecting the user.**

**Improved Authentication Logic:**

The login process **now checks for user credentials stored in local storage**. This enhancement allows the application to **authenticate users based on data added by the signup page**, ensuring that both login and signup functionalities work together effectively.
The authenticate method now verifies user credentials against 
 users array stored in local storage, providing a more dynamic and flexible authentication mechanism.
Seamless User Experience:

With these changes, users can now sign up and log in without any issues, allowing for a smooth transition between the two functionalities. The application now handles user authentication properly, ensuring that users can access the application as intended.
These improvements significantly enhance the overall user experience and ensure that the login functionality operates reliably within the application.
img1

**login before any valid username and passoword**

img3
img2

**login after matching values**

### CODE REVIEW

**Comment by sakeel-103** [comment]
This branch has a conflict issue.
Please review the code, as the "refactor backend code to use middleware functions" has been added.
If I'm not mistaken, the data is now being stored in MongoDB.

Plz Check PR #37
Issue #36  

based on that, proceed with your task.
and implement your "Fix Login Functionality and Redirect Logic" accordingly.

I apologize for this please go through codes once again !!!!

**Comment by Dipu2552003** [comment]
Thank you for your feedback regarding PR #37 and Issue #36.

I have implemented the following changes:

   - Resolved the conflicts and ensured that the login functionality is now
   using local storage authentication instead of hardcoded credentials.
   - The frontend is set up to allow users to log in without needing to
   input credentials each time, improving user experience.
   - Ensured that the login logic is properly connected to the form
   submission with <form id="loginForm" #form="ngForm"
   (ngSubmit)="login(form)">.

However, I noticed that the frontend is still not directly connected to the
backend. Currently, the authentication process relies on hardcoded
credentials (username: test, password: password). I suggest integrating the
backend authentication mechanism to enhance security and ensure that the
login process is more scalable and robust.

This integration would be beneficial for future developments and improve
the overall architecture of the application.

Please let me know your thoughts or if you would like me to proceed with
implementing this connection.

Thank you for your guidance!

Best regards,
Dipkul

**Review by sakeel-103 — COMMENTED** [review]
Please review your codes and implementation as the signup/login function is not working properly. After login, it should redirect to the DFS/BFS traversal page, but it is redirecting back to the previous page. Kindly make the necessary corrections and push the commits.

https://github.com/user-attachments/assets/df50afbb-042b-4800-96a2-df576c86e2bf

**Comment by sakeel-103** [comment]
@Dipu2552003 
As the signup/login form functionality is not working correctly, please correct the code and then push your commits. Please correct the implementation.

**Pull request merged**
