### PR TITLE
Replace default favicon

### LINKED ISSUE #237: [Feat]: change favicon of this website , change that to other icon , other than angular icon.
Changing favicon to 
favicon

@sakeel-103  add dssoc and hacktoberfest tag and let us to contribute

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #237

c1

### CODE REVIEW

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Sorry about this, could you please mention issue no. of this PR that you have raised.

**Comment by mehul-m-prajapati** [comment]
> @mehul-m-prajapati Sorry about this, could you please mention issue no. of this PR that you have raised.

@sakeel-103 : I raised issue #222 and PR is already merged by @Jashwanth-rit.
So, I have not pushed my changes for that one.

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
It means you have already done these changes. And it was closed right before

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : The changes were in my local branch. I did not pushed it, yet. 
This guy already opened pr for my issue, so it does not matter now.

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
what is the issue no. of this PR. Please provide so I will assign you the level

**Comment by Jashwanth-rit** [comment]
@mehul-m-prajapati
ok , now you pulled request for mine issue , fine .
Happy coding . cool .

**Pull request merged**
