### PR TITLE
Form aesthetic upgraded and clear feature implemented

### PR DESCRIPTION
**Pull request by LifeHashed**
The clear feature is implemented and minor css has been added to increase aesthetic value

### CODE REVIEW

**Comment by LifeHashed** [comment]
Can you please merge the PR

**Comment by sakeel-103** [comment]
the custom or clear button you've added doesn't look good. Please restore the previous design with only the Clear button, and make sure the fields and button are not enclosed in a div. Also, ensure the layout stays on a single page without scrolling down.

**Comment by LifeHashed** [comment]
@sakeel-103 
Ok sure. I have a suggestion. How about on clicking on the create custom button the page auto scrolls down to show how the graph looks?

**Comment by sakeel-103** [comment]
thank you for the suggestion, I'll consider it if it aligns with the design. 
Work on it.

**Comment by LifeHashed** [comment]
@sakeel-103 thank you

**Pull request merged**
